### ISSUE TITLE
Use both this Jekyll site and BrigadeHub?

### ISSUE THREAD

**Issue by jacebrowning** [citizenlabsgr/homepage#16]
I propose that we continue to build this lightweight static site (accessible from citizenlabs.org) and we map https://github.com/citizenlabsgr/brigadehub to hub.citizienlabs.org with a link from citizenlabs.org.

This has a few advantages: 

- citizenlabs.org will be fast and hopefully never be broken to due code/database issues
- hub.citizienlabs.org can host our dynamic content and can be updated without pushing code
- The https://github.com/brigadehub/brigadehub team seems very active, so we'll get new features for free

Any thoughts on this?

**Comment by Allen616** [comment]
From your perspective is there a different audience or purpose for each site? Would we integrate the two?

**Comment by BrandonKlotz** [comment]
Homepage - peaking interest of a general audience / news / and general information.
Brigade Hub - information relevant to projects / events / and more specific to engagement. There will be overlap in some areas of information.

**Comment by jacebrowning** [comment]
Yeah, I see the goals as:

homepage - get people interested in Citizen Labs
BrigadeHub - help interested people connect with our projects and events

With these goals in mind, the homepage would link to BrigadeHub.

**Comment by Allen616** [comment]
Gotcha.... with ya both on this.

**Comment by jacebrowning** [comment]
https://hub.citizenlabs.org/
