### ISSUE TITLE
Integrate Meetup into Brigadehub

### ISSUE THREAD

**Issue by Allen616** [citizenlabsgr/homepage#19]
Integrate Meetup so that upcoming events appear in upper right hand corner automatically, rather then the current method of adding events.

**Comment by jacebrowning** [comment]
The link to Meetup works now. Did you have anything else in mind?

**Comment by Allen616** [comment]
Yes, I think the Meetup events will feed into site for upcoming meetings.

**Comment by jacebrowning** [comment]
Does that happen automatically now or do we need to do something else?

**Comment by Allen616** [comment]
It is not doing it automatically. There are somethings on the Admin side to do this under the "Manage Brigade" section. Not sure if the links or additionally farther down on the page it asks for Meetup Oauth keys. Meetup provides different keys, not sure which one to use for Brigadehub.

**Comment by jacebrowning** [comment]
I can look into it.

**Comment by jacebrowning** [comment]
We just need to click "sync events" periodically. It seems tow be working.
