### ISSUE TITLE
Use SSL for the site

### ISSUE THREAD

**Issue by jacebrowning** [citizenlabsgr/homepage#3]
Being able to use https://citizenlabs.org will look more professional.

https://www.cloudflare.com is a good way to do this for free. We could create a Citizen Labs account for this.

**Comment by jacebrowning** [comment]
This is working now:

http://www.citizenlabs.org => https://citizenlabs.org
http://grparks.citizenlabs.org => https://grparks.citizenlabs.org
http://openbudgetgr.citizenlabs.org => https://openbudgetgr.citizenlabs.org

**Comment by Allen616** [comment]
I am not able to log into Brigadehub website. When I click on "Login" it takes me to a Heroku error page  that says that nothing is there, yet.

**Comment by Allen616** [comment]
I am seeing that after the Github authentication attempt Heroku is returning me to the old Heroku app name, not the one we added hub to last night.

**Comment by Allen616** [comment]
This is the error url ''' http://citizen-labs.herokuapp.com/auth/github/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch
'''

**Comment by jacebrowning** [comment]
Try removing the access for the previous Heroku application: https://github.com/orgs/citizenlabsgr/policies/applications/490492

**Comment by Allen616** [comment]
I can't figure out how to update the access. I can delete the old one, but I am not seeing how to add the new one.

**Comment by jacebrowning** [comment]
I opened an issue with the maintainers: https://github.com/brigadehub/brigadehub/issues/510

**Comment by jacebrowning** [comment]
@Allen616 When you get a chance, can you try updating our OAuth settings: https://github.com/brigadehub/brigadehub/issues/510#issuecomment-295475667

**Comment by jacebrowning** [comment]
I think this is working now. I am able to log in: https://hub.citizenlabs.org/login
