### ISSUE TITLE
Projects table not loading

### ISSUE THREAD

**Issue by jacebrowning** [citizenlabsgr/homepage#36]
I know we haven't shared this page yet, but the projects aren't loading on https://citizenlabs.org/projects:

  
<img width="990" alt="screen shot 2017-08-31 at 10 46 13 am" src="https://user-images.githubusercontent.com/939501/29929491-a3b2dec4-8e39-11e7-92e9-bcc7f5d58b59.png">

**Comment by Allen616** [comment]
I will delete this. I think it was caused by changes I made to the table I was using.
