### ISSUE TITLE
Make 'gh-pages' the 'master'

### ISSUE THREAD

**Issue by jacebrowning** [citizenlabsgr/homepage#6]
I think this code would be less confusing to work on if we got rid of the existing README (which doesn't actually control the website's content) and make `gh-pages` the new `master` branch.

Thoughts? @Allen616 @BrandonKlotz

**Comment by Allen616** [comment]
agreed.

**Comment by jacebrowning** [comment]
@BrandonKlotz, now there is only one branch, `master`. CSS color changes will reflected on our homepage.
